dist: trusty
language: rust
sudo: required

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: nightly

jobs:
  include:
    - stage: Linux
      rust: nightly
      env:
        - TARGET=x86_64-unknown-linux-gnu
    - stage: MacOSX
      env:
        - TARGET=x86_64-apple-darwin
      os: osx
      rust: nightly
    - stage: codecoverage
      env:
        - TARGET=x86_64-unknown-linux-gnu
      rust: nightly
      script: ./codecov.sh

before_install:
  - set -e
  - rustup self update

script:
  - cargo test

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - master
